"""track_embeddings

Revision ID: 11a88449793b
Revises: f576cad55826
Create Date: 2026-08-21 09:50:42.889650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '11a88449793b'
down_revision: Union[str, None] = 'f576cad55826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('reid_identity_id', sa.Uuid(), nullable=False),
    sa.Column('local_track_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_embeddings_camera_id'), 'track_embeddings', ['camera_id'], unique=False)
    op.create_index(op.f('ix_track_embeddings_captured_at'), 'track_embeddings', ['captured_at'], unique=False)
    op.create_index(op.f('ix_track_embeddings_reid_identity_id'), 'track_embeddings', ['reid_identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_embeddings_reid_identity_id'), table_name='track_embeddings')
    op.drop_index(op.f('ix_track_embeddings_captured_at'), table_name='track_embeddings')
    op.drop_index(op.f('ix_track_embeddings_camera_id'), table_name='track_embeddings')
    op.drop_table('track_embeddings')
    # ### end Alembic commands ###
